### ISSUE TITLE
Passwords with spaces

### ISSUE THREAD

**Issue by tchapi** [Sorunome/mx-puppet-skype#15]
Hello

Skype accounts with passwords with a regular space (` `) in it does not work. I think this is due to:

https://github.com/Sorunome/mx-puppet-skype/blob/0255283d5aebbc8340d9f1ed389e3d91960925fe/src/index.ts#L120

I have tested to put the password in quotes but to no avail (_which is pretty logical I suppose_)

Thanks a lot !
Best regards

**Comment by tchapi** [comment]
To fix that, maybe add an option to provide the credentials in base64 for instance ? Because having another delimiter would just break with passwords that contain this specific character anyway

Or support quoted credentials. But I think this is more convoluted and could lead to edge cases (I guess this functionality would be implemented with a little regex)

**Comment by tchapi** [comment]
Hi @Sorunome 

Any hint on that ? I'm happy to make a PR if you're ok with the base64 idea

BR

**Comment by Sorunome** [comment]
base64 encoding that doesn't seem user-friendly.

As the password is the last parameter it could just join all last parameters with a space?

**Comment by tchapi** [comment]
You're right that it's not user-friendly. Are we sure that the login part cannot contain any whitespace character ? If this is the case, your solution if fine

**Comment by Sorunome** [comment]
absolutely no idea :/

**Comment by tchapi** [comment]
As per the actual Microsoft register process, it's likely that the login is either `[a-zA-Z1-9]`, or an email, so that should be fine !

**Comment by tchapi** [comment]
Do you want me to make a PR for this ?

**Comment by Sorunome** [comment]
if you want to, it'd be great!

27. 1. 2021 19:54:00 tchap <notifications@github.com>:

**Comment by tchapi** [comment]
I'll let you review https://github.com/Sorunome/mx-puppet-skype/pull/16 and test it to see if it works well for you :)
