### ISSUE TITLE
feature request: ability to reply to a skype-message 

### ISSUE THREAD

**Issue by bendschs** [Sorunome/mx-puppet-skype#3]
Bridge answers with the following message in skype, when replying to something on matrix side.

> In reply to @_skypepuppet__8=3alive=3username:matrix.server.com 
> Textmessage

**Comment by Sorunome** [comment]
implemented in https://github.com/Sorunome/mx-puppet-skype/commit/3f161b27cb67e2a15d3932374e8b1603ff701182
