### ISSUE TITLE
bridge seems to stop sending/receiving after a few hours

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-skype#5]
really hard to get to the bottom of this one. Nothing in the logs when it fails (just 
```
Apr-30 03:15:09.096 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:20:09.179 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:25:09.279 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:30:09.353 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:35:09.454 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:40:09.518 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:45:09.615 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:50:09.706 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 03:55:09.778 [SkypePuppet:client] verbose: Getting contacts diff....
Apr-30 04:00:09.809 [SkypePuppet:client] verbose: Getting contacts diff....
```
)

and it works again after restarting the bridge, for a while. Anything I could do to get more logs of the problem?

**Comment by Sorunome** [comment]
Could it be that in those moments web.skype.com also isn't live updating the messages for that particular account?

**Comment by ericmigi** [comment]
So to test if I can receive messages, I get my friend to send me a message. I also check on web.skype.com to confirm that his message arrived. the web app does show the message. I'm not sure that's the problem here.

**Comment by ericmigi** [comment]
oh interesting! sounds like web.skype is bad :)

In this case I did see the messages immediately in skype without reloading. I will see if I can replicate it again

**Comment by ericmigi** [comment]
ok just ran into problem again. Checked web.skype.com and it correctly displayed incoming message, but the bridge didn't and has no error/warning. The bridge had been restarted 30 minutes before.

**Comment by ericmigi** [comment]
no problems in last few weeks
